services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mongodb
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - ecoride-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: MattLi2024!!
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: secure_password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - ecoride-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: creditsPlateforme
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecoride-network

networks:
  ecoride-network:
    driver: bridge

volumes:
  db_data:
  mongodb_data: